server:
  port: 8085
  servlet:
    context-path: /query-sample/api
spring:
  application:
    name: query-server
  data:
    mongodb:
      host: localhost
      port: 27017

axon:
  serializer:
    general: jackson
  eventhandling:
    processors:
      "[BalanceProcessor]":
        mode: tracking
        source: streamableKafkaMessageSource
  kafka:
    client-id: balance-consumer
    default-topic: axon-events
    consumer:
      event-processor-mode: tracking
      group-id: query-group
      bootstrap-servers: localhost:9092
